defmodule Mix.Tasks.Fugue.Color.Gen do
  @shortdoc "Generate lib/fugue/color/wcs.ex from synced Timbre WCS JSON"

  @moduledoc """
  Code-generates `Fugue.Color.WCS` from the World Color Survey artifacts that
  Timbre drops into `priv/color/wcs/*.json`.

  `priv/color/` is gitignored scratch (see `.gitignore`); the runtime data lives
  *inlined* in the generated `lib/fugue/color/wcs.ex`, which is committed. So a
  checkout without `priv/color/` still compiles. Regenerate after Timbre changes:

      # in the Timbre repo
      make sync-fugue FUGUE=/path/to/fugue
      # in this repo
      mix fugue.color.gen

  The emitted module is run through `Code.format_string!/1` with deterministic
  ordering, so re-running on unchanged inputs produces no diff.

  Only the WCS chromatic grid is consumed: rows B-I (light to dark) x columns
  1-40 -> the 40x8 grid the section 5 splash expects. The achromatic column 0
  and the A0/J0 caps are dropped.
  """

  use Mix.Task

  # Filename -> {atom, display order}. Order here is the language-toggle order.
  @languages [
    {"tarahumara-central.json", :tarahumara},
    {"kalam.json", :kalam},
    {"nafaanra.json", :nafaanra},
    {"walpiri.json", :walpiri}
  ]

  # WCS value rows, light (B, value 8) to dark (I, value 2). Index = lightness l.
  @rows ~w(B C D E F G H I)
  @hue_count 40
  @lightness_count 8

  @out "lib/fugue/color/wcs.ex"

  @impl Mix.Task
  def run(_args) do
    Application.ensure_all_started(:jason)
    dir = Path.join([File.cwd!(), "priv", "color", "wcs"])

    langs =
      Enum.map(@languages, fn {file, atom} ->
        path = Path.join(dir, file)

        unless File.exists?(path) do
          Mix.raise(
            "missing #{path}. Run `make sync-fugue FUGUE=#{File.cwd!()}` in the Timbre repo first."
          )
        end

        {atom, path |> File.read!() |> Jason.decode!()}
      end)

    source = render(langs)
    out = Path.join(File.cwd!(), @out)
    File.write!(out, source)
    Mix.shell().info("generated #{@out} from #{length(langs)} WCS languages")
  end

  defp render(langs) do
    atoms = Enum.map(langs, fn {atom, _} -> atom end)

    labels =
      for {atom, j} <- langs, into: %{} do
        {atom, j |> Map.fetch!("language") |> squish()}
      end

    # chips: %{lang => %{{h, l} => {code, consensus}}}, only the chromatic grid.
    chips =
      for {atom, j} <- langs, into: %{} do
        chip_map = Map.fetch!(j, "chips")

        grid =
          for l <- 0..(@lightness_count - 1),
              h <- 0..(@hue_count - 1),
              into: %{} do
            id = Enum.at(@rows, l) <> Integer.to_string(h + 1)
            c = Map.fetch!(chip_map, id)
            {{h, l}, {Map.fetch!(c, "modal_term"), Map.fetch!(c, "consensus")}}
          end

        {atom, grid}
      end

    # terms: distinct modal winners in the grid, ordered by frequency desc then code.
    terms =
      for {atom, grid} <- chips, into: %{} do
        ordered =
          grid
          |> Map.values()
          |> Enum.frequencies_by(fn {code, _} -> code end)
          |> Enum.sort_by(fn {code, n} -> {-n, code} end)
          |> Enum.map(fn {code, _} -> code end)

        {atom, ordered}
      end

    # Per-language color + transcription, restricted to the terms actually used.
    term_colors =
      for {atom, j} <- langs, into: %{} do
        colors = Map.fetch!(j, "term_colors")
        {atom, Map.new(terms[atom], fn code -> {code, Map.fetch!(colors, code)} end)}
      end

    transcriptions =
      for {atom, j} <- langs, into: %{} do
        tr = Map.fetch!(j, "term_transcriptions")
        {atom, Map.new(terms[atom], fn code -> {code, squish(Map.fetch!(tr, code))} end)}
      end

    body = """
    # GENERATED by `mix fugue.color.gen` from Timbre priv/color/wcs/*.json.
    # Do not edit by hand; re-run the task instead.
    defmodule Fugue.Color.WCS do
      @moduledoc \"\"\"
      Real World Color Survey chip aggregations for the color chapter section 5.

      Generated from Timbre's per-language WCS artifacts: each chromatic chip on
      the 40 hue x 8 lightness grid carries the modal term most speakers reached
      for and the consensus fraction that agreed. Term codes (e.g. `"M"`) decode
      to native transcriptions through `term_label/2`.

      Languages: #{Enum.map_join(atoms, ", ", &Atom.to_string/1)}.
      Regenerate with `mix fugue.color.gen` after Timbre changes.
      \"\"\"

      @hue_count #{@hue_count}
      @lightness_count #{@lightness_count}

      def hue_count, do: @hue_count
      def lightness_count, do: @lightness_count

      @languages #{inspect(atoms)}
      def languages, do: @languages

      @labels #{render_map(labels, atoms)}
      def language_label(lang), do: Map.fetch!(@labels, lang)

      @terms #{render_terms(terms, atoms)}
      @doc "Modal-winning term codes used in `lang`'s grid, by descending frequency."
      def terms(lang), do: Map.fetch!(@terms, lang)

      @term_colors #{render_code_maps(term_colors, atoms)}
      @doc "Representative sRGB hex for term `code` in `lang`."
      def term_color(lang, code), do: @term_colors |> Map.fetch!(lang) |> Map.fetch!(code)

      @transcriptions #{render_code_maps(transcriptions, atoms)}
      @doc "Native-language transcription for term `code` in `lang`."
      def term_label(lang, code), do: @transcriptions |> Map.fetch!(lang) |> Map.fetch!(code)

      @chips #{render_chips(chips, atoms)}
      @doc "Modal term code + consensus (0..1] for `lang` at chip (h, l)."
      def modal(lang, h, l), do: @chips |> Map.fetch!(lang) |> Map.fetch!({h, l})

      @doc "Approximate base sRGB backdrop for a chip at hue index h and lightness row l."
      def chip_color(h, l) do
        lambda = 380 + h / @hue_count * 320.0
        base = Fugue.Color.Spectrum.hex(lambda)
        blend_lightness(base, l)
      end

      defp blend_lightness("#" <> hex, l) do
        {r, g, b} = parse(hex)
        t = (l + 0.5) / @lightness_count

        {wr, wg, wb} =
          cond do
            t < 0.5 ->
              k = (0.5 - t) * 2
              {r + (255 - r) * k, g + (255 - g) * k, b + (255 - b) * k}

            true ->
              k = (t - 0.5) * 2
              {r * (1 - k), g * (1 - k), b * (1 - k)}
          end

        "#" <> byte(wr) <> byte(wg) <> byte(wb)
      end

      defp parse(<<r1, r2, g1, g2, b1, b2>>) do
        {String.to_integer(<<r1, r2>>, 16), String.to_integer(<<g1, g2>>, 16),
         String.to_integer(<<b1, b2>>, 16)}
      end

      defp byte(v) do
        v = round(v) |> max(0) |> min(255)
        s = Integer.to_string(v, 16)
        if byte_size(s) == 1, do: "0" <> s, else: s
      end
    end
    """

    body
    |> Code.format_string!()
    |> IO.iodata_to_binary()
    |> Kernel.<>("\n")
  end

  # ---- literal rendering (deterministic ordering) ----

  defp render_map(map, atoms) do
    inner =
      Enum.map_join(atoms, ", ", fn a -> "#{inspect(a)} => #{inspect(map[a])}" end)

    "%{" <> inner <> "}"
  end

  defp render_terms(terms, atoms) do
    inner =
      Enum.map_join(atoms, ", ", fn a -> "#{inspect(a)} => #{inspect(terms[a])}" end)

    "%{" <> inner <> "}"
  end

  defp render_code_maps(maps, atoms) do
    inner =
      Enum.map_join(atoms, ", ", fn a ->
        codes =
          maps[a]
          |> Enum.sort_by(fn {code, _} -> code end)
          |> Enum.map_join(", ", fn {code, v} -> "#{inspect(code)} => #{inspect(v)}" end)

        "#{inspect(a)} => %{#{codes}}"
      end)

    "%{" <> inner <> "}"
  end

  defp render_chips(chips, atoms) do
    inner =
      Enum.map_join(atoms, ", ", fn a ->
        cells =
          chips[a]
          |> Enum.sort_by(fn {{h, l}, _} -> {l, h} end)
          |> Enum.map_join(", ", fn {{h, l}, {code, cons}} ->
            "{#{h}, #{l}} => {#{inspect(code)}, #{inspect(cons)}}"
          end)

        "#{inspect(a)} => %{#{cells}}"
      end)

    "%{" <> inner <> "}"
  end

  defp squish(s), do: s |> String.split() |> Enum.join(" ")
end
