defmodule FugueWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :fugue

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_fugue_key",
    signing_salt: "3DQyTS7+",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # In dev, serve bloom's wasm pkg directly from the source tree so
  # `wasm-pack build` output is visible on page refresh without re-running
  # `mix assets.setup`. Registered before the main Plug.Static so it takes
  # precedence for `/vendor/bloom/*`. Prod serves the copied version from
  # priv/static (via `mix assets.deploy`).
  if code_reloading? do
    plug Plug.Static,
      at: "/vendor/bloom",
      from: Path.expand("../../assets/vendor/bloom/pkg", __DIR__),
      gzip: false,
      only: ~w(bloom.js bloom_bg.wasm bloom.d.ts)
  end

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :fugue,
    gzip: not code_reloading?,
    only: FugueWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug FugueWeb.Router
end
